### PR TITLE
fix and update

### PR DESCRIPTION
**Pull request by JoaoMartins-callmeJohn**
.net core updated to 3.1, NewtonsoftJson updated to 3.1.10 and Forge updated to 1.8.0.
media.AddListener() changed to media.AddEventListener() as the first one is deprecated.
Lots of divs were being created to store google.maps.Map. A block of code was added to remove any div previously created before appending a new one.

### CODE REVIEW

**Comment by augustogoncalves** [comment]
thanks for the fixes.

about the Google Maps extensions, can you please fix & use this: https://github.com/Autodesk-Forge/forge-extensions/tree/master/public/extensions/GoogleMapsLocator

**Comment by JoaoMartins-callmeJohn** [comment]
Done!
There was no need for the fix on the map extension anymore.
I kept the Google Maps API key hardcoded (as in the original file).

**Comment by augustogoncalves** [comment]
seems to happen on Chrome (works on Safari), ideas?

image

**Comment by JoaoMartins-callmeJohn** [comment]
Adding the event name as an argument (load would be a good choice).
I tried with click for testing and it didn't trigger the function...

**Pull request merged**
